In [ ]:
#API Call of Ocean Warming Data
import requests

# New API URL
url = "https://global-warming.org/api/ocean-warming-api"

try:
    # Make the API request
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()  # Parse the JSON response

        # Extract the result dictionary from the data
        result = data['result']

        # Convert string values to floats
        ocean_warming_data = {year: float(value) for year, value in result.items()}

        print("Ocean warming data:")
        for year, value in ocean_warming_data.items():
            print(f"Year: {year}, Ocean Warming: {value}°C")
    else:
        print(f"API request failed with status code: {response.status_code}")
except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")

In [ ]:
# API URL
url = "https://global-warming.org/api/ocean-warming-api"

try:
    # Make the API request
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()  # Parse the JSON response

        # Extract years from the 'result' dictionary
        years = [year for year in data['result'].keys()]

        # Count the number of entries (years)
        num_entries = len(years)

        print(f"Number of entries (years): {num_entries}")
    else:
        print(f"API request failed with status code: {response.status_code}")
except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")

In [ ]:
import csv

# New API URL
url = "https://global-warming.org/api/ocean-warming-api"

try:
    # Make the API request
    response = requests.get(url)

    # Check if the request was successful
    if response.status_code == 200:
        data = response.json()  # Parse the JSON response

        # Extract the result dictionary from the data
        result = data['result']

        # Convert string values to floats
        ocean_warming_data = {year: float(value) for year, value in result.items()}

        # Save data to a CSV file
        with open("ocean_warming_data.csv", mode="w", newline="") as csv_file:
            csv_writer = csv.writer(csv_file)
            csv_writer.writerow(["Year", "Ocean Warming (°C)"])  # Write header
            for year, value in ocean_warming_data.items():
                csv_writer.writerow([year, value])

        print("Ocean warming data saved to ocean_warming_data.csv")
    else:
        print(f"API request failed with status code: {response.status_code}")
except requests.exceptions.RequestException as e:
    print(f"An error occurred: {e}")

In [ ]:
# Specify the path to your CSV file
csv_file_path = "ocean_warming_data.csv"

try:
    # Read the CSV file and create a DataFrame
    df = pd.read_csv(csv_file_path)  # Skip the first 4 rows

    # Display the DataFrame
    print(df)
except FileNotFoundError:
    print(f"File '{csv_file_path}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")

In [141]:
# Read the tab-separated CSV file
oceanwarming_df = pd.read_csv("ocean_warming_data.csv")

# Display the DataFrame
oceanwarming_df

     Year  Ocean Warming (°C)
0    1880               -0.02
1    1881                0.04
2    1882                0.03
3    1883               -0.04
4    1884               -0.12
..    ...                 ...
138  2018                0.66
139  2019                0.74
140  2020                0.72
141  2021                0.63
142  2022                0.67

[143 rows x 2 columns]

In [ ]:
import csv

# Specify the path to your CSV file
csv_file_path = "Global_Land_OceanTemp_Anom.csv"

try:
    # Open and read the CSV file
    with open(csv_file_path, "r") as csv_file:
        csv_reader = csv.reader(csv_file)  # Create a CSV reader object
        
        # Skip the first 5 rows
        for _ in range(5):
            next(csv_reader)

        # Loop through each row starting from the 6th row
        for row in csv_reader:
            # Process the row as needed
            print(row)
except FileNotFoundError:
    print(f"File '{csv_file_path}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
import pandas as pd

# Specify the path to your CSV file
csv_file_path = "Global_Land_OceanTemp_Anom.csv"

try:
    # Read the CSV file and create a DataFrame
    df = pd.read_csv(csv_file_path, skiprows=4)  # Skip the first 4 rows

    # Display the DataFrame
    print(df)
except FileNotFoundError:
    print(f"File '{csv_file_path}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
# Specify the path to your CSV file
csv_file_path = "Global_Land_Temp_Anom.csv"

try:
    # Open and read the CSV file
    with open(csv_file_path, "r") as csv_file:
        csv_reader = csv.reader(csv_file)  # Create a CSV reader object
        
        # Skip the first 5 rows
        for _ in range(5):
            next(csv_reader)

        # Loop through each row starting from the 6th row
        for row in csv_reader:
            # Process the row as needed
            print(row)
except FileNotFoundError:
    print(f"File '{csv_file_path}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
import pandas as pd

# Specify the path to your CSV file
csv_file_path = "Global_Land_Temp_Anom.csv"

try:
    # Read the CSV file and create a DataFrame
    df = pd.read_csv(csv_file_path, skiprows=4)  # Skip the first 4 rows

    # Display the DataFrame
    print(df)
except FileNotFoundError:
    print(f"File '{csv_file_path}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
# Specify the path to your CSV file
csv_file_path = "Global_Ocean_Temp_Anom.csv"

try:
    # Open and read the CSV file
    with open(csv_file_path, "r") as csv_file:
        csv_reader = csv.reader(csv_file)  # Create a CSV reader object
        
        # Skip the first 5 rows
        for _ in range(5):
            next(csv_reader)

        # Loop through each row starting from the 6th row
        for row in csv_reader:
            # Process the row as needed
            print(row)
except FileNotFoundError:
    print(f"File '{csv_file_path}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")

In [ ]:
# Specify the path to your CSV file
csv_file_path = "Global_Ocean_Temp_Anom.csv"

try:
    # Read the CSV file and create a DataFrame
    df = pd.read_csv(csv_file_path, skiprows = 4)  # Skip the first 4 rows

    # Display the DataFrame
    print(df)
except FileNotFoundError:
    print(f"File '{csv_file_path}' not found.")
except Exception as e:
    print(f"An error occurred: {e}")

In [142]:
import pandas as pd

# Read the tab-separated CSV file
landocean_df = pd.read_csv("Global_Land_OceanTemp_Anom.csv",skiprows=4, delimiter=',')

# Display the DataFrame
landocean_df

        Year  Anomaly
0     185001    -0.39
1     185002    -0.15
2     185003    -0.26
3     185004    -0.22
4     185005    -0.21
...      ...      ...
2078  202303     1.23
2079  202304     0.98
2080  202305     0.96
2081  202306     1.07
2082  202307     1.12

[2083 rows x 2 columns]

In [143]:
# Read the tab-separated CSV file
landocean_df = pd.read_csv("Global_Land_Temp_Anom.csv",skiprows=4, delimiter=',')

# Display the DataFrame
landocean_df

        Year  Anomaly
0     185001    -1.03
1     185002    -0.33
2     185003    -0.56
3     185004    -0.51
4     185005    -0.53
...      ...      ...
2078  202303     2.20
2079  202304     1.25
2080  202305     1.20
2081  202306     1.39
2082  202307     1.40

[2083 rows x 2 columns]

In [144]:
# Read the tab-separated CSV file
landocean_df = pd.read_csv("Global_Ocean_Temp_Anom.csv",skiprows=4, delimiter=',')

# Display the DataFrame
landocean_df

        Year  Anomaly
0     185001    -0.11
1     185002    -0.07
2     185003    -0.12
3     185004    -0.09
4     185005    -0.07
...      ...      ...
2078  202303     0.80
2079  202304     0.85
2080  202305     0.84
2081  202306     0.92
2082  202307     0.99

[2083 rows x 2 columns]

In [ ]:
from datetime import datetime
# Replace 1850 with the valid year you have
year = 1850
try:
    date_object = datetime(year, 1, 1)
    print("Date:", date_object.strftime("%Y-%m-%d"))
except ValueError:
    print("Invalid year")

In [ ]:
from datetime import datetime
# Replace 1850 with the valid year you have
year = 1920
try:
    date_object = datetime(year, 1, 1)
    print("Date:", date_object.strftime("%Y-%m-%d"))
except ValueError:
    print("Invalid year")